### PR TITLE
Revert "Changes"

### PR DESCRIPTION
**Pull request by username1565**
I don't know how to delete this revert changes... Just button pressed, and I cann't understand what version I have now...

### CODE REVIEW

**Comment by TheChiefMeat** [comment]
Do you want to revert the previous commits you made?

**Comment by TheChiefMeat** [comment]
If you're unsure of what version you have, the best thing to do would be to simply delete your existing fork and re-fork the project, that way you'll be up to date.

**Comment by TheChiefMeat** [comment]
If you want me to remove this pull request, just reply here to let me know.

**Comment by username1565** [comment]
1. I want to delete "revert change commit", because this was been activated by pressing ONE button.
2. I want to save previous version with changes.
3. I don't want to you do revert previous changes.
4. I want to make changes from previous code, this is last synchronized pull request.

Also, I'm fixing file-names now.

**Comment by TheChiefMeat** [comment]
Understood.

This commit will be deleted and not merged with the latest release. All your previous commits will still be available as of the last previous commit. If you have any issues with your current fork, I'd recommend you delete you fork and re-fork from the latest build.

**Comment by username1565** [comment]
Ok, I see this.
You can enable "Issues" for this in the settings for project.

Then, I think development will be better.

**Comment by TheChiefMeat** [comment]
I enabled issues for you if you'd like to use them.

**Comment by username1565** [comment]
I did just delete this from "branches", and set last version as "default branch". Now this commit is inactive.

**Pull request closed without merging**
