### PR TITLE
Changes, additions and fixing.

### PR DESCRIPTION
**Pull request by username1565**
- Add default filename.
- Add functions to working with file-names.
- Add tooltip to the buttons with filename included.
- Add default filename if message input as text.
- Add bin prefix for filenames if this downloading as binary.
- Now base64 encoded files available as txt-files.
- Fix "Message failed to verify" alert notification. If encrypted message try to verify Key not found in this case. If checksum mismatch - alert displayed now.
- Test decryption without check signature, for signed_and_encrypted, and try to got encrypted message after check signature.
	Big commentary in decrypt+verify function added. https://github.com/TheChiefMeat/pgp/issues/7
- Found Generators incompatibility. Just leave this here, as todo note. https://github.com/TheChiefMeat/pgp/issues/8
- Many tests made with different files and keys. There is possible to make Jasmine-test.

Have a nice day.

### CODE REVIEW

**Comment by username1565** [comment]
- Now signed message can be verified by priv, in (verify+)decrypt tab.

**Comment by TheChiefMeat** [comment]
I like everything except for the tooltips. There's a few spelling mistakes in them and I feel like they're rather redundant and not needed. If you could remove the tooltips then I'll go ahead and merge these commits.

**Comment by username1565** [comment]
What text and where need to delete?
I did tooltips for buttons, where including the filename,
because filename is different for different actions,
containing in attribute download for buttons and in tooltip this is available for display.

**Comment by TheChiefMeat** [comment]
Mostly the hover over tooltips for the windows.

**Pull request merged**
